on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: Start LocalStack
        uses: LocalStack/setup-localstack@v0.2.2
        with:
          image-tag: 'latest'
          install-awslocal: 'true'
      - name: Run tests
        run: go test -v ./...
        env:
          # localstack requires these environment variables
          AWS_DEFAULT_REGION: ap-northeast-1
          # Credentials are important for localstack
          # Without them, the tests will fail like:
          #   operation error S3: CreateBucket, get identity: get credentials: failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, failed to get API token, operation error ec2imds: getToken, http response error StatusCode: 400, request to EC2 IMDS failed
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
